# Generated by Django 4.2.2 on 2023-07-01 06:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(default="", max_length=100)),
                ("prenom", models.CharField(default="", max_length=100)),
                ("email", models.EmailField(default="", max_length=254, unique=True)),
                ("numero_telephone", models.CharField(default="", max_length=20)),
                ("mot_de_passe", models.CharField(default="", max_length=128)),
                ("promotion", models.CharField(default="", max_length=2)),
                (
                    "Code_confirmation",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
            ],
            options={
                "db_table": "admin",
            },
        ),
        migrations.CreateModel(
            name="CoursProgrammer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jour", models.CharField(max_length=100)),
                ("promotion", models.CharField(max_length=128)),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                ("matiere", models.CharField(max_length=150)),
                ("salle", models.CharField(max_length=150)),
                ("teacher", models.CharField(default="", max_length=128)),
            ],
            options={
                "db_table": "coursProgrammer",
            },
        ),
        migrations.CreateModel(
            name="Matiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("enseignant", models.CharField(max_length=128)),
                ("timing", models.IntegerField(default=0)),
                ("Informations", models.CharField(max_length=500)),
                ("promotion", models.CharField(default="", max_length=28)),
            ],
            options={
                "db_table": "Matiere",
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "annee",
                    models.CharField(
                        choices=[
                            ("L1", "Licence 1"),
                            ("L2", "Licence 2"),
                            ("L3", "Licence 3"),
                            ("M1", "Master 1"),
                            ("M2", "Master 2"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "groupe",
                    models.CharField(
                        blank=True,
                        choices=[("G1", "Groupe 1"), ("G2", "Groupe 2")],
                        max_length=2,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "Promotion",
            },
        ),
        migrations.CreateModel(
            name="Salle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "Salle",
            },
        ),
        migrations.CreateModel(
            name="CoursProgrammerL1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Date",
                    models.CharField(
                        default="10/05/2023",
                        max_length=128,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le format de date doit être jj/mm/aaaa.",
                                regex="^\\d{2}/\\d{2}/\\d{4}$",
                            )
                        ],
                    ),
                ),
                ("jour", models.CharField(max_length=128)),
                ("promotion", models.CharField(max_length=128)),
                ("heure_debut", models.CharField(max_length=150)),
                ("heure_fin", models.CharField(max_length=150)),
                ("salle", models.CharField(max_length=150)),
                ("teacher", models.CharField(default="", max_length=128)),
                ("groupe", models.CharField(max_length=128)),
                (
                    "matiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EditTimeplan.matiere",
                    ),
                ),
            ],
            options={
                "db_table": "coursProgrammerL1",
            },
        ),
    ]
