# Generated by Django 4.2.2 on 2023-06-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EditTimeplan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoursProgrammer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jour", models.CharField(max_length=100)),
                ("promotion", models.CharField(max_length=128)),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField()),
                ("matiere", models.CharField(max_length=150)),
                ("salle", models.CharField(max_length=150)),
                ("teacher", models.CharField(default="", max_length=128)),
            ],
            options={
                "db_table": "coursProgrammer",
            },
        ),
        migrations.CreateModel(
            name="CoursProgrammerL1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("promotion", models.CharField(max_length=128)),
                ("heure_debut", models.CharField(max_length=150)),
                ("heure_fin", models.CharField(max_length=150)),
                ("matiere", models.CharField(max_length=150)),
                ("salle", models.CharField(max_length=150)),
                ("teacher", models.CharField(default="", max_length=128)),
                ("groupe", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "coursProgrammerL1",
            },
        ),
        migrations.AddField(
            model_name="adminuser",
            name="promotion",
            field=models.CharField(default="", max_length=2),
        ),
        migrations.AlterField(
            model_name="adminuser",
            name="Code_confirmation",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterModelTable(
            name="adminuser",
            table="admin",
        ),
        migrations.AlterModelTable(
            name="matiere",
            table="Matiere",
        ),
        migrations.AlterModelTable(
            name="promotion",
            table="Promotion",
        ),
        migrations.AlterModelTable(
            name="salle",
            table="Salle",
        ),
        migrations.DeleteModel(
            name="EmploiDuTemps",
        ),
    ]
