# Generated by Django 4.2.2 on 2023-06-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EditTimeplan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmploiDuTemps',
            new_name='CoursProgrammer',
        ),
        migrations.AlterModelTable(
            name='coursprogrammer',
            table='coursProgrammer',
        ),
        migrations.AlterModelTable(
            name='matiere',
            table='Matiere',
        ),
        migrations.AlterModelTable(
            name='promotion',
            table='Promotion',
        ),
        migrations.AlterModelTable(
            name='salle',
            table='Salle',
        ),
    ]
