# Generated by Django 4.2.2 on 2023-06-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditTimeplan', '0002_rename_emploidutemps_coursprogrammer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='promotion',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='Code_confirmation',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
