# Generated by Django 4.2.2 on 2023-06-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditTimeplan', '0003_adminuser_promotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursprogrammer',
            name='matiere',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='coursprogrammer',
            name='salle',
            field=models.CharField(max_length=150),
        ),
    ]
