# Generated by Django 4.2.2 on 2023-06-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EditTimeplan", "0003_coursprogrammerl1_jour"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursprogrammerl1",
            name="Date",
            field=models.DateField(default="2023-05-10"),
        ),
        migrations.AlterField(
            model_name="coursprogrammerl1",
            name="jour",
            field=models.CharField(max_length=128),
        ),
    ]
