# Generated by Django 4.2.2 on 2023-06-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditTimeplan', '0004_alter_coursprogrammer_matiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursprogrammer',
            name='teacher',
            field=models.CharField(default='', max_length=128),
        ),
    ]
