# Generated by Django 4.2.2 on 2023-06-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditTimeplan', '0005_coursprogrammer_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursprogrammer',
            name='heure_debut',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='coursprogrammer',
            name='heure_fin',
            field=models.CharField(max_length=150),
        ),
    ]
