# Generated by Django 4.2.2 on 2023-06-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditTimeplan', '0006_alter_coursprogrammer_heure_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursprogrammer',
            name='promotion',
            field=models.CharField(max_length=128),
        ),
    ]
