# Generated by Django 4.2.2 on 2023-06-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditTimeplan', '0007_alter_coursprogrammer_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursprogrammer',
            name='heure_debut',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='coursprogrammer',
            name='heure_fin',
            field=models.TimeField(),
        ),
    ]
