# Generated by Django 4.2.2 on 2023-06-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditTimeplan', '0008_alter_coursprogrammer_heure_debut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursprogrammer',
            name='heure_debut',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='coursprogrammer',
            name='heure_fin',
            field=models.CharField(max_length=150),
        ),
    ]
