# Generated by Django 4.2.2 on 2023-06-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditTimeplan', '0009_alter_coursprogrammer_heure_debut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursProgrammerL1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=100)),
                ('promotion', models.CharField(max_length=128)),
                ('heure_debut', models.CharField(max_length=150)),
                ('heure_fin', models.CharField(max_length=150)),
                ('matiere', models.CharField(max_length=150)),
                ('salle', models.CharField(max_length=150)),
                ('teacher', models.CharField(default='', max_length=128)),
                ('groupe', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'coursProgrammerL1',
            },
        ),
    ]
