# Generated by Django 4.2.2 on 2023-06-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditTimeplan', '0010_coursprogrammerl1'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursprogrammer',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
