# Generated by Django 4.2.2 on 2023-06-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Etudiants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date_de_naissance", models.DateField()),
                ("Email", models.EmailField(max_length=254)),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
