# Generated by Django 4.2.2 on 2023-07-04 00:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "EditTimeplan",
            "0002_filiere_coursprogrammer_date_matiere_heur_restant_and_more",
        ),
        ("showtimeplan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoursProgrammerEtu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Date",
                    models.CharField(
                        default="10/05/2023",
                        max_length=128,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le format de date doit être jj/mm/aaaa.",
                                regex="^\\d{2}/\\d{2}/\\d{4}$",
                            )
                        ],
                    ),
                ),
                ("jour", models.CharField(max_length=100)),
                ("promotion", models.CharField(max_length=128)),
                ("heure_debut", models.CharField(max_length=150)),
                ("heure_fin", models.CharField(max_length=150)),
                ("salle", models.CharField(max_length=150)),
                ("teacher", models.CharField(default="", max_length=128)),
                (
                    "filiere",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EditTimeplan.filiere",
                    ),
                ),
                (
                    "matiere",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EditTimeplan.matiere",
                    ),
                ),
            ],
            options={
                "db_table": "coursProgrammerEtu",
            },
        ),
    ]
