# Generated by Django 4.2.2 on 2023-06-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimeplan', '0002_rename_etudiants_user_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_de_naissance',
        ),
        migrations.AddField(
            model_name='user',
            name='confirmer_mot_de_passe',
            field=models.CharField(default='', editable=False, max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='mot_de_passe',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='numero_telephone',
            field=models.CharField(default=555, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
