# Generated by Django 4.2.2 on 2023-06-17 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtimeplan', '0003_remove_user_email_remove_user_date_de_naissance_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
