# Generated by Django 4.2.2 on 2023-06-30 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("showtimeplan", "0005_delete_coursprogrammeretu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursprogrammerl1etu",
            name="Date",
            field=models.CharField(
                default="10/05/2023",
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le format de date doit être jj/mm/aaaa.",
                        regex="^\\d{2}/\\d{2}/\\d{4}$",
                    )
                ],
            ),
        ),
    ]
