# Generated by Django 4.2.2 on 2023-06-17 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimeplan', '0006_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nom',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='prenom',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
