# Generated by Django 4.2.2 on 2023-06-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showtimeplan', '0007_alter_user_nom_alter_user_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmer_mot_de_passe',
        ),
        migrations.AddField(
            model_name='user',
            name='code_de_confirmation',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
